### ISSUE TITLE
test_communication fails during AOT with PackageCompiler

### ISSUE THREAD

**Issue by binary132** [JuliaEditorSupport/LanguageServer.jl#328] opened 2019-01-24 15:56 UTC
Julia 1.1.0 2019-01-21
`PackageCompiler#master`
`LanguageServer#master`

```jl
julia> using PackageCompiler; compile_package("LanguageServer")
Launching new julia process to run commands...
LanguageServer: Error During Test at /Users/x/.julia/packages/LanguageServer/GNDpW/test/runtests.jl:6
  Got exception outside of a @test
  LoadError: IOError: write: broken pipe (EPIPE)
  Stacktrace:
   [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at /Users/x/.julia/packages/PackageCompiler/F7Wvf/sysimg/backup/native/sys.dylib:?
   [2] wait() at /Users/x/.julia/packages/PackageCompiler/F7Wvf/sysimg/backup/native/sys.dylib:?
   [3] uv_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at /Users/x/.julia/packages/PackageCompiler/F7Wvf/sysimg/backup/native/sys.dylib:?
   [4] unsafe_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at /Users/x/.julia/packages/PackageCompiler/F7Wvf/sysimg/backup/native/sys.dylib:?
   [5] write_transport_layer(::Base.PipeEndpoint, ::String, ::Bool) at ./gcutils.jl:87
   [6] write_transport_layer(::Base.PipeEndpoint, ::String) at /Users/x/.julia/packages/LanguageServer/GNDpW/src/languageserverinstance.jl:82
   [7] top-level scope at /Users/x/.julia/packages/LanguageServer/GNDpW/test/test_communication.jl:92
   [8] include_relative(::Module, ::String) at /Users/x/.julia/packages/PackageCompiler/F7Wvf/sysimg/backup/native/sys.dylib:?
   [9] include(::Module, ::String) at ./sysimg.jl:29
   [10] include(::String) at ./client.jl:403
   [11] top-level scope at /Users/x/.julia/packages/LanguageServer/GNDpW/test/runtests.jl:9
   [12] top-level scope at /Applications/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
   [13] top-level scope at /Users/x/.julia/packages/LanguageServer/GNDpW/test/runtests.jl:8
   [14] include_relative(::Module, ::String) at /Users/x/.julia/packages/PackageCompiler/F7Wvf/sysimg/backup/native/sys.dylib:?
   [15] include(::Module, ::String) at ./sysimg.jl:29
   [16] include(::String) at ./client.jl:403
   [17] top-level scope at /Users/x/.julia/packages/PackageCompiler/F7Wvf/src/snooping.jl:23
   [18] eval at ./boot.jl:328 [inlined]
   [19] top-level scope at ./none:3
   [20] eval(::Module, ::Any) at /Users/x/.julia/packages/PackageCompiler/F7Wvf/sysimg/backup/native/sys.dylib:?
   [21] exec_options(::Base.JLOptions) at ./client.jl:243
   [22] _start() at ./client.jl:436
  in expression starting at /Users/x/.julia/packages/LanguageServer/GNDpW/test/test_communication.jl:91
Test Summary:  | Pass  Error  Total
LanguageServer |   27      1     28
ERROR: LoadError: Some tests did not pass: 27 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /Users/jsolxm206/.julia/packages/LanguageServer/GNDpW/test/runtests.jl:6
done.
Tuple{getfield(Main, Symbol("##3#4"))} contains a blacklisted substring
```

**Comment by rsrock** [comment] 2019-01-27 17:10
I just ran into this myself.  This is actually a straight up test failure, it appears on Travis too.

**Comment by davidanthoff** [comment] 2019-01-28 18:57
I'll close this as a duplicate of https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/289.

**Closed by davidanthoff** 2019-01-28 18:57 UTC
Labels: bug

**Comment by rsrock** [comment] 2019-01-28 19:46
But note that it's not just a Travis issue, the package tests fail locally too

**Comment by davidanthoff** [comment] 2019-01-29 17:54
Yeah, I'm updating the title of that other issues to just fix tests :)
