### ISSUE TITLE
file2pathuri(::Void) error

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/LanguageServer.jl#251] opened 2018-01-18 10:59 UTC
Setting up a project as in the discourse post: https://discourse.julialang.org/t/vs-code-intellisense-issues/8437/6?u=kristoffer.carlsson I get:

```
INFO: Set(String["/Users/kristoffer/Documents/testvscode"])
INFO: parsed /Users/kristoffer/Documents/testvscode/file1.jl
INFO: parsed /Users/kristoffer/Documents/testvscode/file2.jl
ERROR: LoadError: MethodError: no method matching filepath2uri(::Void)
Closest candidates are:
  filepath2uri(!Matched::String) at /Users/kristoffer/.vscode/extensions/julialang.language-julia-0.9.1/scripts/languageserver/packages/LanguageServer/src/utilities.jl:187
Stacktrace:
 [1] process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/definition")},LanguageServer.TextDocumentPositionParams}, ::LanguageServer.LanguageServerInstance) at /Users/kristoffer/.vscode/extensions/julialang.language-julia-0.9.1/scripts/languageserver/packages/LanguageServer/src/provider_definitions.jl:35
 [2] run(::LanguageServer.LanguageServerInstance) at /Users/kristoffer/.vscode/extensions/julialang.language-julia-0.9.1/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:38
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:305
 [6] _start() at ./client.jl:371
```

**Comment by davidanthoff** [comment] 2018-01-18 18:03
I can't reproduce this, but I might not have the exact right repo case. I created the two files as julbinb described it on discourse, with the content she had there, right? @KristofferC if you have a zip file with the exact files that trigger this for you handy, would you mind putting it up as a gist or emailing it to me or something?

**Comment by ZacLN** [comment] 2018-01-18 18:10
I couldn’t rep this on either master or 0.9.1

**Comment by KristofferC** [comment] 2018-01-18 21:40
Ok, so what I had to do was change the `using GraphAux` to

```
import GraphAux: Vertex
```

and then Ctrl-clicking Vertex in 

```
struct Graph{T}
    vertices :: Vector{Vertex{T}}
    bars:: Vector{NonExisting}
end
```

sometimes it works but sometimes I also got the error in the first post.

**Comment by KristofferC** [comment] 2018-01-18 21:44
https://github.com/JuliaEditorSupport/LanguageServer.jl/blob/master/src/provider_definitions.jl#L27, the call to `Base.find_source_file` can return `nothing` so that should probably be handled.

**Comment by ZacLN** [comment] 2018-01-18 21:50
Great, thanks for tracking that down Kristoffer

**Comment by davidanthoff** [comment] 2018-01-27 05:22
This is fixed, right? Closing for now.

**Closed by davidanthoff** 2018-01-27 05:22 UTC
Labels: bug
